name: ngwallet
description: A sample CLI wallet to NGIN.
version: 0.1.0
homepage: https://ngin.sh

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  sha3: ^0.1.1
  hex: ^0.1.2
  args: ^1.6.0
  fast_base58: ^0.1.9
  jsonrpc2: ^2.0.3+1
  secp256k1: ^0.1.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
